# Basics

In [3]:
import numpy as np

In [4]:
a = np.array([1, 2, 3], dtype='int8') # <- for managing size
print(a)

[1 2 3]


In [5]:
b = np.array([[9.1,8.2,7.3],[6.4,5.5,4.6]])
print(b)

[[9.1 8.2 7.3]
 [6.4 5.5 4.6]]


In [6]:
# Get dimensions
print(a.ndim)
print(b.ndim)

1
2


In [7]:
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [8]:
# Get Type
print(a.dtype)
print(b.dtype)

int8
float64


In [9]:
#Get size
print(a.itemsize)
print(a.size)
print(a.nbytes) # Same as above two multiplied

print(b.itemsize)
print(b.size)
print(b.nbytes) # Same as above two multiplied


1
3
3
8
6
48


# Getting / Setting

In [10]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# Get specific element [r, c]
a[1, -5]

10

In [12]:
# Get specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# Specific column
a[:,2]

array([ 3, 10])

In [14]:
# Fancier [startindex:endindex:stepsize]
a[0, 1:6:2] #same as
a[0, 1:-1:2]

array([2, 4, 6])

In [15]:
# Reassign
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [16]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [17]:
#3d example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
# Work from outside in. [matrix,row,column]. Get 4:
print(b[0,1,1])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4


# Initializing

In [18]:
# All 0 Matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
# All 1
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
# Any other number. Shape then value
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [22]:
# full_like. Preexisting shape then value
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [23]:
# Random decimal #s
np.random.rand(4,2) # notice only one set of parens here

array([[0.50737713, 0.20238394],
       [0.0895221 , 0.16275598],
       [0.40384914, 0.38328192],
       [0.92792695, 0.96985665]])

In [24]:
# Random integers
z = np.random.randint(100, size=(3,3)) #(min), max, size
print(z)

[[90  8 14]
 [80 27 97]
 [72  6 28]]


In [25]:
# Identity matrix
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [26]:
z2 = np.repeat(z, 3, axis=1)
z2

array([[90, 90, 90,  8,  8,  8, 14, 14, 14],
       [80, 80, 80, 27, 27, 27, 97, 97, 97],
       [72, 72, 72,  6,  6,  6, 28, 28, 28]])

E.g. How to make a 5x5 matrix with all ones on the outside, 9 in the middle and the rest zeroes

In [27]:
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9

output[1:-1,1:-1] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Copying arrays, don't do b = a. changing one will overwrite the other

In [28]:
# Instead,
a = np.array([1,2,3,])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


# Mathematics

In [29]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [30]:
# Element-wise operations
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)
print(a ** 2)


[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]


In [31]:
np.sin(a)
np.cos(a)
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

## Linear Algebra
### [Reference](https://numpy.org/doc/stable/reference/routines.linalg.html)

In [32]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

# Matrix multiplication
# a * b won't work because dimensions are different

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [33]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

## Statistics  

In [34]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
np.min(stats)

1

In [36]:
np.max(stats)
np.max(stats, axis=1)

array([3, 6])

In [37]:
np.sum(stats)

21

## Reorganizing arrays

In [38]:
# Reshape - must be same # of values
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [39]:
# Vertical stacking
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
# Horizontal stacking
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Misc.

In [41]:
# Load data from file
filedata = np.genfromtxt('numpy_intro_data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [11, 12, 21, 22, 33, 44, 55, 66]], dtype=int32)

#### Boolean Masking and Advanced Indexing

In [43]:
filedata > 10

array([[False, False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [44]:
filedata[filedata > 10]

array([11, 12, 21, 22, 33, 44, 55, 66], dtype=int32)

In [53]:
# Challenge
a = np.arange(1,31)
matrix1 = a.reshape(6,5)
print(matrix1)

# Select 11, 12, 16 & 17
subset = matrix1[2:4,0:2]
print(subset)

# Select 2, 8, 14, 20
subset2 = matrix1[[0,1,2,3],[1,2,3,4]]
subset2

# Select 4, 5, 24, 25, 29, 30
subset3 = matrix1[[0,4,5], 3:6]
subset3

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[11 12]
 [16 17]]


array([[ 4,  5],
       [24, 25],
       [29, 30]])