In [19]:
import numpy as np
import math

# 1. 1D Array

In [20]:
# Create a 1-dimensional NumPy array with elements [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].

arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
# Calculate the sum and average of the array elements.

print(np.sum(arr1))
print(np.mean(arr1))

55
5.5


In [22]:
# Multiply the array by a scalar value of 3.

print(arr1 * 3)

[ 3  6  9 12 15 18 21 24 27 30]


In [23]:
# Slice the array to select elements from the 3rd to the 7th position.
arr1slice = arr1[2:7]
arr1slice

array([3, 4, 5, 6, 7])

In [24]:
# Compute the sum and average of the sliced array

print(np.sum(arr1slice))
print(np.mean(arr1slice))

25
5.0


# 2. Multi-dimensional Array

In [25]:
# Create a 3x3 matrix with the following rows in order: {3,4,5} {6,7,8} {9,1,2}

m1 = np.array([[3,4,5],[6,7,8],[9,1,2]])
m1


array([[3, 4, 5],
       [6, 7, 8],
       [9, 1, 2]])

In [26]:
# Print the element in the second row, third column.

print(m1[1,2])

8


In [27]:
# Print the second row

print(m1[1,:])

[6 7 8]


In [28]:
# Print the second column

print(m1[:,1])

[4 7 1]


In [29]:
# Compute the transpose of the matrix
m1t = np.transpose(m1)
print(m1t)

[[3 6 9]
 [4 7 1]
 [5 8 2]]


# 3. Concatenation

In [30]:
# Create two 1-d arrays: [5,1,4,2] and [6,10,11,7]

a1 = np.array([5,1,4,2])
a2 = np.array([6,10,11,7])

In [31]:
# Concatenate the two arrays
a3 = np.concatenate((a1, a2))
a3

array([ 5,  1,  4,  2,  6, 10, 11,  7])

In [32]:
# Sort the new array from lowest to highest
a4 = np.sort(a3)
a4

array([ 1,  2,  4,  5,  6,  7, 10, 11])

In [33]:
# Split the result from the previous step into two equal sized arrays
a5 = np.split(a4, 2)
a5

[array([1, 2, 4, 5]), array([ 6,  7, 10, 11])]

# 4. Mathematical Functions


In [34]:
# Create an array with values from 0 to 4*pi in increments of pi/2 (pi refers to the mathematical constant  π)
arr4pi = np.arange(0, (4 * np.pi + 1), (np.pi / 2))
arr4pi

array([ 0.        ,  1.57079633,  3.14159265,  4.71238898,  6.28318531,
        7.85398163,  9.42477796, 10.99557429, 12.56637061])

In [35]:
# Compute an array that applies the mathematical sin function to the original array
sinPi = np.sin(arr4pi)
sinPi

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
       -2.4492936e-16,  1.0000000e+00,  3.6739404e-16, -1.0000000e+00,
       -4.8985872e-16])

In [42]:
# Do the same for the following mathematical functions: cos, log, exp
cosPi = np.cos(arr4pi)
logPi = np.log(arr4pi)
expPi = np.exp(arr4pi)
print(cosPi)
print(logPi)
print(expPi)

[ 1.0000000e+00  6.1232340e-17 -1.0000000e+00 -1.8369702e-16
  1.0000000e+00  3.0616170e-16 -1.0000000e+00 -4.2862638e-16
  1.0000000e+00]
[      -inf 0.45158271 1.14472989 1.55019499 1.83787707 2.06102062
 2.24334217 2.39749285 2.53102425]
[1.00000000e+00 4.81047738e+00 2.31406926e+01 1.11317778e+02
 5.35491656e+02 2.57597050e+03 1.23916478e+04 5.96097415e+04
 2.86751313e+05]


/var/folders/g1/q7h4_80969x88nl9r_y_rvx80000gn/T/ipykernel_2232/23101988.py:3: RuntimeWarning: divide by zero encountered in log
  logPi = np.log(arr4pi)


In [37]:
# Compute the mean, median, and standard deviation of each resultant array
print(np.mean(sinPi))
print(np.median(sinPi))
print(np.std(sinPi))

print(np.mean(cosPi))
print(np.median(cosPi))
print(np.std(cosPi))

print(np.mean(logPi))
print(np.median(logPi))
print(np.std(logPi))

print(np.mean(expPi))
print(np.median(expPi))
print(np.std(expPi))

-2.975712385932333e-17
0.0
0.6666666666666666
0.11111111111111106
6.123233995736766e-17
0.7370277311900889
-inf
1.8378770664093453
nan
40222.7148375631
535.4916555247646
89056.36419225672


/usr/local/lib/python3.11/site-packages/numpy/core/_methods.py:173: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)


# 5. Boolean Indexing and Filtering


In [38]:
# Create a 1-d array with all multiples of 5 from 15 to 80, and also include 12
arr5z = np.arange(15, 81, 5)
arr5y = np.append(arr5z, 12)
arr5x = np.sort(arr5y)
arr5x

array([12, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80])

In [39]:
# Create a boolean array that identifies elements which are greater than 25
arr5xz = arr5x > 25
arr5xz

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [40]:
# Use that boolean array to filter out elements greater than 25 from the original array.
arr5x[~arr5xz]

array([12, 15, 20, 25])